version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: |
          yarn
          yarn build
      - run:
        name: Deploy with Now
        command: ./node_modules/.bin/now -t ${NOW_TOKEN} && now -t ${NOW_TOKEN} alias



