version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn global add now && now -t ${NOW_TOKEN} && now -t ${NOW_TOKEN} alias



